version: 2

updates:

  - package-ecosystem: docker
    directory: /prepare/base
    schedule:
      interval: weekly
    open-pull-requests-limit: 0  # only security updates

  - package-ecosystem: docker
    directory: /prepare/resources
    schedule:
      interval: weekly
    open-pull-requests-limit: 0  # only security updates

  - package-ecosystem: docker
    directory: /run/mangosd
    schedule:
      interval: weekly
    open-pull-requests-limit: 0  # only security updates

  - package-ecosystem: docker
    directory: /run/realmd
    schedule:
      interval: weekly
    open-pull-requests-limit: 0  # only security updates
