version: '3'

services:

  db:
    container_name: vmangos-db
    image: vmangos-db:${VMANGOS_COMMIT_ID}
    build:
      context: ./run/db
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    # Increase max packet size, as some queries are large
    command: --max_allowed_packet=128M
    healthcheck:
      # Custom healthcheck using file created by ./run/db/init.sh
      test: bash -c "[ -f /var/lib/mysql/healthy ]"
      interval: 5s
      retries: 20
    volumes:
      # MySQL data volume for persistence
      - ./volumes/mysql:/var/lib/mysql
      # MySQL init script to create databases and insert data
      - ./run/db/init.sh:/docker-entrypoint-initdb.d/init.sh
      # Read only volume of database dump files
      - ./volumes/db:/db:ro
    networks:
      - backend

  mangosd:
    container_name: vmangos-mangosd
    image: vmangos-mangosd:${VMANGOS_COMMIT_ID}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    build:
      context: ./run/mangosd
      dockerfile: Dockerfile
      args:
        VMANGOS_COMMIT_ID: ${VMANGOS_COMMIT_ID}
    ports:
      - 8085:8085
    volumes:
      # Copy over the mangosd binary
      - ./volumes/mangosd:/vmangos/bin
      # Location of extracted client data (maps, mmaps etc.)
      - ./volumes/client_data:/vmangos/client_data/:ro
    networks:
      - frontend
      - backend

  realmd:
    container_name: vmangos-realmd
    image: vmangos-realmd:${VMANGOS_COMMIT_ID}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    build:
      context: ./run/realmd
      dockerfile: Dockerfile
      args:
        VMANGOS_COMMIT_ID: ${VMANGOS_COMMIT_ID}
    ports:
      - 3724:3724
    volumes:
      # Copy over the realmd binary
      - ./volumes/realmd:/vmangos/bin
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
