version: '3'

services:

  core:
    container_name: vmangos_core
    image: ubuntu:22.04
    restart: no
    build:
      context: ./core
      dockerfile: Dockerfile-run
    volumes:
      - ./volumes/resources:/vmangos/resources
